// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: testdata/example.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_example_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testdata_example_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0}
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_testdata_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Person) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Person) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Employees     []*Person              `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FoundedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=founded_at,json=foundedAt,proto3" json:"founded_at,omitempty"`
	Uptime        *durationpb.Duration   `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_testdata_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{1}
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetEmployees() []*Person {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *Company) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Company) GetFoundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FoundedAt
	}
	return nil
}

func (x *Company) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Child         *Nested                `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	Children      []*Nested              `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_testdata_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{2}
}

func (x *Nested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Nested) GetChild() *Nested {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *Nested) GetChildren() []*Nested {
	if x != nil {
		return x.Children
	}
	return nil
}

type WKTTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    *structpb.Struct       `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WKTTest) Reset() {
	*x = WKTTest{}
	mi := &file_testdata_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WKTTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WKTTest) ProtoMessage() {}

func (x *WKTTest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WKTTest.ProtoReflect.Descriptor instead.
func (*WKTTest) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{3}
}

func (x *WKTTest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *WKTTest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WKTTest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

type AllTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoubleField   float64                `protobuf:"fixed64,1,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	FloatField    float32                `protobuf:"fixed32,2,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	Int32Field    int32                  `protobuf:"varint,3,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field    int64                  `protobuf:"varint,4,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field   uint32                 `protobuf:"varint,5,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field   uint64                 `protobuf:"varint,6,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field   int32                  `protobuf:"zigzag32,7,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field   int64                  `protobuf:"zigzag64,8,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field  uint32                 `protobuf:"fixed32,9,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field  uint64                 `protobuf:"fixed64,10,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field int32                  `protobuf:"fixed32,11,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field int64                  `protobuf:"fixed64,12,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	BoolField     bool                   `protobuf:"varint,13,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	StringField   string                 `protobuf:"bytes,14,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	BytesField    []byte                 `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTypes) Reset() {
	*x = AllTypes{}
	mi := &file_testdata_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTypes) ProtoMessage() {}

func (x *AllTypes) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTypes.ProtoReflect.Descriptor instead.
func (*AllTypes) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{4}
}

func (x *AllTypes) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *AllTypes) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *AllTypes) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *AllTypes) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *AllTypes) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *AllTypes) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *AllTypes) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *AllTypes) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *AllTypes) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *AllTypes) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *AllTypes) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *AllTypes) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *AllTypes) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *AllTypes) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *AllTypes) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

var File_testdata_example_proto protoreflect.FileDescriptor

const file_testdata_example_proto_rawDesc = "" +
	"\n" +
	"\x16testdata/example.proto\x12\btestdata\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/field_mask.proto\"\x84\x01\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.testdata.StatusR\x06status\"\xb5\x02\n" +
	"\aCompany\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\temployees\x18\x02 \x03(\v2\x10.testdata.PersonR\temployees\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.testdata.Company.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"founded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfoundedAt\x121\n" +
	"\x06uptime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x06Nested\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x05child\x18\x02 \x01(\v2\x10.testdata.NestedR\x05child\x12,\n" +
	"\bchildren\x18\x03 \x03(\v2\x10.testdata.NestedR\bchildren\"\xa0\x01\n" +
	"\aWKTTest\x127\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12.\n" +
	"\x04mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"\x97\x04\n" +
	"\bAllTypes\x12!\n" +
	"\fdouble_field\x18\x01 \x01(\x01R\vdoubleField\x12\x1f\n" +
	"\vfloat_field\x18\x02 \x01(\x02R\n" +
	"floatField\x12\x1f\n" +
	"\vint32_field\x18\x03 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x04 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x05 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x06 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\a \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\b \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\t \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\n" +
	" \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\v \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\f \x01(\x10R\rsfixed64Field\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesField*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02B(Z&github.com/apstndb/protoon-go/testdatab\x06proto3"

var (
	file_testdata_example_proto_rawDescOnce sync.Once
	file_testdata_example_proto_rawDescData []byte
)

func file_testdata_example_proto_rawDescGZIP() []byte {
	file_testdata_example_proto_rawDescOnce.Do(func() {
		file_testdata_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_example_proto_rawDesc), len(file_testdata_example_proto_rawDesc)))
	})
	return file_testdata_example_proto_rawDescData
}

var file_testdata_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_example_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_testdata_example_proto_goTypes = []any{
	(Status)(0),                   // 0: testdata.Status
	(*Person)(nil),                // 1: testdata.Person
	(*Company)(nil),               // 2: testdata.Company
	(*Nested)(nil),                // 3: testdata.Nested
	(*WKTTest)(nil),               // 4: testdata.WKTTest
	(*AllTypes)(nil),              // 5: testdata.AllTypes
	nil,                           // 6: testdata.Company.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*structpb.Struct)(nil),       // 9: google.protobuf.Struct
	(*structpb.Value)(nil),        // 10: google.protobuf.Value
	(*fieldmaskpb.FieldMask)(nil), // 11: google.protobuf.FieldMask
}
var file_testdata_example_proto_depIdxs = []int32{
	0,  // 0: testdata.Person.status:type_name -> testdata.Status
	1,  // 1: testdata.Company.employees:type_name -> testdata.Person
	6,  // 2: testdata.Company.metadata:type_name -> testdata.Company.MetadataEntry
	7,  // 3: testdata.Company.founded_at:type_name -> google.protobuf.Timestamp
	8,  // 4: testdata.Company.uptime:type_name -> google.protobuf.Duration
	3,  // 5: testdata.Nested.child:type_name -> testdata.Nested
	3,  // 6: testdata.Nested.children:type_name -> testdata.Nested
	9,  // 7: testdata.WKTTest.attributes:type_name -> google.protobuf.Struct
	10, // 8: testdata.WKTTest.value:type_name -> google.protobuf.Value
	11, // 9: testdata.WKTTest.mask:type_name -> google.protobuf.FieldMask
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_testdata_example_proto_init() }
func file_testdata_example_proto_init() {
	if File_testdata_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_example_proto_rawDesc), len(file_testdata_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_example_proto_goTypes,
		DependencyIndexes: file_testdata_example_proto_depIdxs,
		EnumInfos:         file_testdata_example_proto_enumTypes,
		MessageInfos:      file_testdata_example_proto_msgTypes,
	}.Build()
	File_testdata_example_proto = out.File
	file_testdata_example_proto_goTypes = nil
	file_testdata_example_proto_depIdxs = nil
}
